[package]
name = "browser-automation-example"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <you@example.com>"]
description = "A simple browser automation agent using Fantoccini"
license = "MIT" # 可选

# 启用二进制（可执行程序）
[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
# 浏览器自动化客户端 (WebDriver for Rust)
fantoccini = "0.22.0"
tokio = { version = "1.0", features = ["full"] }

anyhow = "1.0"
thiserror = "1.0"