[package]
name = "magentic_backend"
version = "0.1.0"
edition = "2021"
authors = ["AaronBen"]
description = "A simple backend for the Magentic project."

# 启用二进制（可执行程序）
[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4"] }
chrono = { version = "0.4", features = ["serde", "clock"] }
fantoccini = "0.22.0"
tokio = { version = "1.0", features = ["full"] }
axum = { version = "0.6", features = ["macros", "json"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
anyhow = "1.0"
thiserror = "1.0"
futures-core = "0.3"

[dev-dependencies]
tower = "0.4"

[dependencies.tokio-stream]
version = "0.1"
features = ["sync"]